//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails
{
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class Exception : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("Exception", "https://www.mycas.org.uk/services/ChangePersonalDetailsService");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class ServiceException : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ServiceException", "https://www.mycas.org.uk/services/ChangePersonalDetailsService");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.mycas.org.uk/services/ChangePersonalDetailsService", ConfigurationName="CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.ChangePersonalDet" +
        "ailsService")]
    public interface ChangePersonalDetailsService
    {
        
        // CODEGEN: Generating message contract since the operation updatePersonalDetail is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="https://www.mycas.org.uk/services/updatePersonalDetail", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.Exception), Action="https://www.mycas.org.uk/services/updatePersonalDetail", Name="Exception")]
        [System.ServiceModel.FaultContractAttribute(typeof(CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.ServiceException), Action="https://www.mycas.org.uk/services/updatePersonalDetail", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.updatePersonalDetailResponse1 updatePersonalDetail(CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.updatePersonalDetailRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.mycas.org.uk/services/ChangePersonalDetailsService")]
    public partial class updatePersonalDetail
    {
        
        private ChangePersonalDetailsRequest changePersonalDetailsRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ChangePersonalDetailsRequest changePersonalDetailsRequest
        {
            get
            {
                return this.changePersonalDetailsRequestField;
            }
            set
            {
                this.changePersonalDetailsRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.mycas.org.uk/schemas/ChangePersonalDetailsTypes")]
    public partial class ChangePersonalDetailsRequest
    {
        
        private RequestBody requestBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RequestBody RequestBody
        {
            get
            {
                return this.requestBodyField;
            }
            set
            {
                this.requestBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.mycas.org.uk/schemas/ChangePersonalDetailsTypes")]
    public partial class RequestBody
    {
        
        private PreferredName preferredNameField;
        
        private string nickNameField;
        
        private Contact contactField;
        
        private UCRNType uCRNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PreferredName PreferredName
        {
            get
            {
                return this.preferredNameField;
            }
            set
            {
                this.preferredNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NickName
        {
            get
            {
                return this.nickNameField;
            }
            set
            {
                this.nickNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Contact Contact
        {
            get
            {
                return this.contactField;
            }
            set
            {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public UCRNType UCRN
        {
            get
            {
                return this.uCRNField;
            }
            set
            {
                this.uCRNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.mycas.org.uk/schemas/CommonTypes")]
    public partial class PreferredName
    {
        
        private string preferredFirstNameField;
        
        private string preferredMiddleNameField;
        
        private string preferredLastNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PreferredFirstName
        {
            get
            {
                return this.preferredFirstNameField;
            }
            set
            {
                this.preferredFirstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PreferredMiddleName
        {
            get
            {
                return this.preferredMiddleNameField;
            }
            set
            {
                this.preferredMiddleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PreferredLastName
        {
            get
            {
                return this.preferredLastNameField;
            }
            set
            {
                this.preferredLastNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.mycas.org.uk/schemas/CommonTypes")]
    public partial class ResponseHead
    {
        
        private string responseCodeField;
        
        private string responseMessageField;
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ResponseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.mycas.org.uk/schemas/ChangePersonalDetailsTypes")]
    public partial class ChangePersonalDetailsResponse
    {
        
        private ResponseHead responseHeadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResponseHead ResponseHead
        {
            get
            {
                return this.responseHeadField;
            }
            set
            {
                this.responseHeadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.mycas.org.uk/services/ChangePersonalDetailsService")]
    public partial class updatePersonalDetailResponse
    {
        
        private ChangePersonalDetailsResponse updatePersonalDetailResponse1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("updatePersonalDetailResponse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ChangePersonalDetailsResponse updatePersonalDetailResponse1
        {
            get
            {
                return this.updatePersonalDetailResponse1Field;
            }
            set
            {
                this.updatePersonalDetailResponse1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.mycas.org.uk/schemas/CommonTypes")]
    public partial class UCRNType
    {
        
        private string uCRNType1Field;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("UCRNType")]
        public string UCRNType1
        {
            get
            {
                return this.uCRNType1Field;
            }
            set
            {
                this.uCRNType1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.mycas.org.uk/schemas/CommonTypes")]
    public partial class Contact
    {
        
        private string mobileNumberField;
        
        private string landlineNumberField;
        
        private string emailAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MobileNumber
        {
            get
            {
                return this.mobileNumberField;
            }
            set
            {
                this.mobileNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string LandlineNumber
        {
            get
            {
                return this.landlineNumberField;
            }
            set
            {
                this.landlineNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string EmailAddress
        {
            get
            {
                return this.emailAddressField;
            }
            set
            {
                this.emailAddressField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updatePersonalDetailRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.mycas.org.uk/services/ChangePersonalDetailsService")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CallerToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.mycas.org.uk/services/ChangePersonalDetailsService", Order=0)]
        public CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.updatePersonalDetail updatePersonalDetail;
        
        public updatePersonalDetailRequest()
        {
        }
        
        public updatePersonalDetailRequest(string CallerToken, CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.updatePersonalDetail updatePersonalDetail)
        {
            this.CallerToken = CallerToken;
            this.updatePersonalDetail = updatePersonalDetail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updatePersonalDetailResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.mycas.org.uk/services/ChangePersonalDetailsService", Order=0)]
        public CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.updatePersonalDetailResponse updatePersonalDetailResponse;
        
        public updatePersonalDetailResponse1()
        {
        }
        
        public updatePersonalDetailResponse1(CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.updatePersonalDetailResponse updatePersonalDetailResponse)
        {
            this.updatePersonalDetailResponse = updatePersonalDetailResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChangePersonalDetailsServiceChannel : CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.ChangePersonalDetailsService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChangePersonalDetailsServiceClient : System.ServiceModel.ClientBase<CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.ChangePersonalDetailsService>, CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.ChangePersonalDetailsService
    {
        
        public ChangePersonalDetailsServiceClient()
        {
        }
        
        public ChangePersonalDetailsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ChangePersonalDetailsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ChangePersonalDetailsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ChangePersonalDetailsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.updatePersonalDetailResponse1 CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.ChangePersonalDetailsService.updatePersonalDetail(CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.updatePersonalDetailRequest request)
        {
            return base.Channel.updatePersonalDetail(request);
        }
        
        public CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.updatePersonalDetailResponse updatePersonalDetail(string CallerToken, CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.updatePersonalDetail updatePersonalDetail1)
        {
            CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.updatePersonalDetailRequest inValue = new CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.updatePersonalDetailRequest();
            inValue.CallerToken = CallerToken;
            inValue.updatePersonalDetail = updatePersonalDetail1;
            CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.updatePersonalDetailResponse1 retVal = ((CASRefreshWebserviceSampleApplication.CAS.ChangePersonalDetails.ChangePersonalDetailsService)(this)).updatePersonalDetail(inValue);
            return retVal.updatePersonalDetailResponse;
        }
    }
}
