//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("https://www.mycas.org.uk/services/QueryUPRNService", ClrNamespace="www.mycas.org.uk.services.QueryUPRNService")]


namespace MyGovScot.MyAccount.QueryUPRNService
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "https://www.mycas.org.uk/services/QueryUPRNService", ConfigurationName = "QueryUPRNService")]
    public interface QueryUPRNService
    {

        // CODEGEN: Generating message contract since the operation queryUPRN is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "https://www.mycas.org.uk/services/queryUPRN", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.mycas.org.uk.services.QueryUPRNService.Exception), Action = "https://www.mycas.org.uk/services/queryUPRN", Name = "Exception")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.mycas.org.uk.services.QueryUPRNService.ServiceException), Action = "https://www.mycas.org.uk/services/queryUPRN", Name = "ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        queryUPRNResponse1 queryUPRN(queryUPRNRequest1 request);

        [System.ServiceModel.OperationContractAttribute(Action = "https://www.mycas.org.uk/services/queryUPRN", ReplyAction = "*")]
        System.Threading.Tasks.Task<queryUPRNResponse1> queryUPRNAsync(queryUPRNRequest1 request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.mycas.org.uk/services/QueryUPRNService")]
    public partial class queryUPRN
    {

        private QueryUPRNRequest queryUPRNRequestField;

        private string callerTokenField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public QueryUPRNRequest queryUPRNRequest
        {
            get
            {
                return this.queryUPRNRequestField;
            }
            set
            {
                this.queryUPRNRequestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string CallerToken
        {
            get
            {
                return this.callerTokenField;
            }
            set
            {
                this.callerTokenField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.mycas.org.uk/schemas/QueryUPRNTypes")]
    public partial class QueryUPRNRequest
    {

        private RequestBody requestBodyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public RequestBody RequestBody
        {
            get
            {
                return this.requestBodyField;
            }
            set
            {
                this.requestBodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.mycas.org.uk/schemas/QueryUPRNTypes")]
    public partial class RequestBody
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Address", typeof(Address), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("UPRN", typeof(UPRNType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.mycas.org.uk/schemas/CommonTypes")]
    public partial class Address
    {

        private string postCodeField;

        private string addressStringField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string PostCode
        {
            get
            {
                return this.postCodeField;
            }
            set
            {
                this.postCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string AddressString
        {
            get
            {
                return this.addressStringField;
            }
            set
            {
                this.addressStringField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.mycas.org.uk/schemas/CommonTypes")]
    public partial class AddressLine
    {

        private string addressLine1Field;

        private string addressLine2Field;

        private string addressLine3Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string AddressLine1
        {
            get
            {
                return this.addressLine1Field;
            }
            set
            {
                this.addressLine1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string AddressLine2
        {
            get
            {
                return this.addressLine2Field;
            }
            set
            {
                this.addressLine2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string AddressLine3
        {
            get
            {
                return this.addressLine3Field;
            }
            set
            {
                this.addressLine3Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.mycas.org.uk/schemas/CommonTypes")]
    public partial class AddressDetails
    {

        private AddressLine addressLineField;

        private string townField;

        private string postCodeField;

        private long lACodeField;

        private bool lACodeFieldSpecified;

        private string addressProviderField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public AddressLine AddressLine
        {
            get
            {
                return this.addressLineField;
            }
            set
            {
                this.addressLineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Town
        {
            get
            {
                return this.townField;
            }
            set
            {
                this.townField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string PostCode
        {
            get
            {
                return this.postCodeField;
            }
            set
            {
                this.postCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public long LACode
        {
            get
            {
                return this.lACodeField;
            }
            set
            {
                this.lACodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LACodeSpecified
        {
            get
            {
                return this.lACodeFieldSpecified;
            }
            set
            {
                this.lACodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string AddressProvider
        {
            get
            {
                return this.addressProviderField;
            }
            set
            {
                this.addressProviderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "Address", Namespace = "https://www.mycas.org.uk/schemas/QueryUPRNTypes")]
    public partial class Address1
    {

        private AddressDetails addressDetailsField;

        private string addressStringField;

        private UPRNType uPRNField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public AddressDetails AddressDetails
        {
            get
            {
                return this.addressDetailsField;
            }
            set
            {
                this.addressDetailsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string AddressString
        {
            get
            {
                return this.addressStringField;
            }
            set
            {
                this.addressStringField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public UPRNType UPRN
        {
            get
            {
                return this.uPRNField;
            }
            set
            {
                this.uPRNField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.mycas.org.uk/schemas/CommonTypes")]
    public partial class UPRNType
    {

        private UPRNTypeUPRNType uPRNType1Field;

        private bool uPRNType1FieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("UPRNType")]
        public UPRNTypeUPRNType UPRNType1
        {
            get
            {
                return this.uPRNType1Field;
            }
            set
            {
                this.uPRNType1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UPRNType1Specified
        {
            get
            {
                return this.uPRNType1FieldSpecified;
            }
            set
            {
                this.uPRNType1FieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.mycas.org.uk/schemas/CommonTypes")]
    public enum UPRNTypeUPRNType
    {

        /// <remarks/>
        P,

        /// <remarks/>
        T,

        /// <remarks/>
        PU,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.mycas.org.uk/schemas/QueryUPRNTypes")]
    public partial class ResponseBody
    {

        private Address1[] matchedAddressDetailsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public Address1[] MatchedAddressDetails
        {
            get
            {
                return this.matchedAddressDetailsField;
            }
            set
            {
                this.matchedAddressDetailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.mycas.org.uk/schemas/CommonTypes")]
    public partial class ResponseHead
    {

        private string responseCodeField;

        private string responseMessageField;

        private bool resultField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string ResponseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public bool Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.mycas.org.uk/schemas/QueryUPRNTypes")]
    public partial class QueryUPRNResponse
    {

        private ResponseHead responseHeadField;

        private ResponseBody responseBodyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public ResponseHead ResponseHead
        {
            get
            {
                return this.responseHeadField;
            }
            set
            {
                this.responseHeadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public ResponseBody ResponseBody
        {
            get
            {
                return this.responseBodyField;
            }
            set
            {
                this.responseBodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.mycas.org.uk/services/QueryUPRNService")]
    public partial class queryUPRNResponse
    {

        private QueryUPRNResponse queryUPRNResponse1Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("queryUPRNResponse", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public QueryUPRNResponse queryUPRNResponse1
        {
            get
            {
                return this.queryUPRNResponse1Field;
            }
            set
            {
                this.queryUPRNResponse1Field = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class queryUPRNRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://www.mycas.org.uk/services/QueryUPRNService", Order = 0)]
        public queryUPRN queryUPRN;

        public queryUPRNRequest1()
        {
        }
        public queryUPRNRequest1(string CallerToken, string UPRN)
        {
            queryUPRN myQueryUPRN = new queryUPRN();
            myQueryUPRN.CallerToken = CallerToken;
            myQueryUPRN.queryUPRNRequest = new QueryUPRNRequest();
            myQueryUPRN.queryUPRNRequest.RequestBody = new RequestBody();
            UPRNType myUPRNType = new UPRNType();
            myUPRNType.Value = UPRN;
            myQueryUPRN.queryUPRNRequest.RequestBody.Item = myUPRNType;
            this.queryUPRN = myQueryUPRN;


        }
        public queryUPRNRequest1(string CallerToken, string addressLine1,string addressLine2,string addressLine3,string town,string postCode)
        {
            if (CallerToken == null|| CallerToken== string.Empty || CallerToken=="")
            {
                throw new System.ArgumentException("Parameter cannot be null", "CallerToken");
            }
            queryUPRN myQueryUPRN = new queryUPRN();
            myQueryUPRN.CallerToken = CallerToken;
            myQueryUPRN.queryUPRNRequest = new QueryUPRNRequest();
            myQueryUPRN.queryUPRNRequest.RequestBody = new RequestBody();
            AddressDetails myAddressDetails = new AddressDetails();
           AddressLine myAddressLine= new AddressLine();
           myAddressLine.AddressLine1 = addressLine1;
           myAddressLine.AddressLine2 = addressLine2;
           myAddressLine.AddressLine3 = addressLine3;
           myAddressDetails.AddressLine = myAddressLine;
           myAddressDetails.PostCode = postCode;
           myAddressDetails.Town = town;
           myAddressDetails.LACodeSpecified = false;
           myQueryUPRN.queryUPRNRequest.RequestBody.Item = myAddressDetails;
            this.queryUPRN = myQueryUPRN;


        }

        public queryUPRNRequest1(queryUPRN queryUPRN)
        {
            this.queryUPRN = queryUPRN;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class queryUPRNResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://www.mycas.org.uk/services/QueryUPRNService", Order = 0)]
        public queryUPRNResponse queryUPRNResponse;

        public queryUPRNResponse1()
        {
        }

        public queryUPRNResponse1(queryUPRNResponse queryUPRNResponse)
        {
            this.queryUPRNResponse = queryUPRNResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryUPRNServiceChannel : QueryUPRNService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryUPRNServiceClient : System.ServiceModel.ClientBase<QueryUPRNService>, QueryUPRNService
    {

        public QueryUPRNServiceClient()
        {
        }

        public QueryUPRNServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public QueryUPRNServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public QueryUPRNServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public QueryUPRNServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        queryUPRNResponse1 QueryUPRNService.queryUPRN(queryUPRNRequest1 request)
        {
            return base.Channel.queryUPRN(request);
        }

        public queryUPRNResponse queryUPRN(queryUPRN queryUPRN1)
        {
            queryUPRNRequest1 inValue = new queryUPRNRequest1();
            inValue.queryUPRN = queryUPRN1;
            queryUPRNResponse1 retVal = ((QueryUPRNService)(this)).queryUPRN(inValue);
            return retVal.queryUPRNResponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<queryUPRNResponse1> QueryUPRNService.queryUPRNAsync(queryUPRNRequest1 request)
        {
            return base.Channel.queryUPRNAsync(request);
        }

        public System.Threading.Tasks.Task<queryUPRNResponse1> queryUPRNAsync(queryUPRN queryUPRN)
        {
            queryUPRNRequest1 inValue = new queryUPRNRequest1();
            inValue.queryUPRN = queryUPRN;
            return ((QueryUPRNService)(this)).queryUPRNAsync(inValue);
        }
    }
    namespace www.mycas.org.uk.services.QueryUPRNService
    {


        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
        [System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
        public partial class Exception : object, System.Xml.Serialization.IXmlSerializable
        {

            private System.Xml.XmlNode[] nodesField;

            private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("Exception", "https://www.mycas.org.uk/services/QueryUPRNService");

            public System.Xml.XmlNode[] Nodes
            {
                get
                {
                    return this.nodesField;
                }
                set
                {
                    this.nodesField = value;
                }
            }

            public void ReadXml(System.Xml.XmlReader reader)
            {
                this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
            }

            public void WriteXml(System.Xml.XmlWriter writer)
            {
                System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
            }

            public System.Xml.Schema.XmlSchema GetSchema()
            {
                return null;
            }

            public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
            {
                System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
                return typeName;
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
        [System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
        public partial class ServiceException : object, System.Xml.Serialization.IXmlSerializable
        {

            private System.Xml.XmlNode[] nodesField;

            private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ServiceException", "https://www.mycas.org.uk/services/QueryUPRNService");

            public System.Xml.XmlNode[] Nodes
            {
                get
                {
                    return this.nodesField;
                }
                set
                {
                    this.nodesField = value;
                }
            }

            public void ReadXml(System.Xml.XmlReader reader)
            {
                this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
            }

            public void WriteXml(System.Xml.XmlWriter writer)
            {
                System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
            }

            public System.Xml.Schema.XmlSchema GetSchema()
            {
                return null;
            }

            public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
            {
                System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
                return typeName;
            }
        }
    }

}