//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("https://www.mycas.org.uk/services/SubscribeUnsubscribeService", ClrNamespace="www.mycas.org.uk.services.SubscribeUnsubscribeService")]

namespace MyGovScot.MyAccount.SubscribeUnsubscribeService
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "https://www.mycas.org.uk/services/SubscribeUnsubscribeService", ConfigurationName = "SubscribeUnsubscribeService")]
    public interface SubscribeUnsubscribeService
    {

        // CODEGEN: Generating message contract since the operation subscribeUnsubscribeService is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "https://www.mycas.org.uk/services/subscribeUnsubscribeService", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.mycas.org.uk.services.SubscribeUnsubscribeService.Exception), Action = "https://www.mycas.org.uk/services/subscribeUnsubscribeService", Name = "Exception")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.mycas.org.uk.services.SubscribeUnsubscribeService.ServiceException), Action = "https://www.mycas.org.uk/services/subscribeUnsubscribeService", Name = "ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        subscribeUnsubscribeServiceResponse1 subscribeUnsubscribeService(subscribeUnsubscribeServiceRequest1 request);

        [System.ServiceModel.OperationContractAttribute(Action = "https://www.mycas.org.uk/services/subscribeUnsubscribeService", ReplyAction = "*")]
        System.Threading.Tasks.Task<subscribeUnsubscribeServiceResponse1> subscribeUnsubscribeServiceAsync(subscribeUnsubscribeServiceRequest1 request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.mycas.org.uk/services/SubscribeUnsubscribeService")]
    public partial class subscribeUnsubscribeService
    {

        private SubscribeUnsubscribeServiceRequest subscribeUnsubscribeServiceRequestField;

        private string callerTokenField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public SubscribeUnsubscribeServiceRequest subscribeUnsubscribeServiceRequest
        {
            get
            {
                return this.subscribeUnsubscribeServiceRequestField;
            }
            set
            {
                this.subscribeUnsubscribeServiceRequestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string CallerToken
        {
            get
            {
                return this.callerTokenField;
            }
            set
            {
                this.callerTokenField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.mycas.org.uk/schemas/SubscribeUnsubscribeServiceTypes")]
    public partial class SubscribeUnsubscribeServiceRequest
    {

        private RequestBody requestBodyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public RequestBody RequestBody
        {
            get
            {
                return this.requestBodyField;
            }
            set
            {
                this.requestBodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.mycas.org.uk/schemas/SubscribeUnsubscribeServiceTypes")]
    public partial class RequestBody
    {

        private long serviceIDField;

        private UCRNType uCRNField;

        private RequestBodyOperationCode operationCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public long ServiceID
        {
            get
            {
                return this.serviceIDField;
            }
            set
            {
                this.serviceIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public UCRNType UCRN
        {
            get
            {
                return this.uCRNField;
            }
            set
            {
                this.uCRNField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public RequestBodyOperationCode OperationCode
        {
            get
            {
                return this.operationCodeField;
            }
            set
            {
                this.operationCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.mycas.org.uk/schemas/CommonTypes")]
    public partial class UCRNType
    {

        private UCRNTypeUCRNType uCRNType1Field;

        private bool uCRNType1FieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("UCRNType")]
        public UCRNTypeUCRNType UCRNType1
        {
            get
            {
                return this.uCRNType1Field;
            }
            set
            {
                this.uCRNType1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UCRNType1Specified
        {
            get
            {
                return this.uCRNType1FieldSpecified;
            }
            set
            {
                this.uCRNType1FieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.mycas.org.uk/schemas/CommonTypes")]
    public enum UCRNTypeUCRNType
    {

        /// <remarks/>
        P,

        /// <remarks/>
        T,

        /// <remarks/>
        PU,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.mycas.org.uk/schemas/CommonTypes")]
    public partial class ResponseHead
    {

        private string responseCodeField;

        private string responseMessageField;

        private bool resultField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string ResponseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public bool Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.mycas.org.uk/schemas/SubscribeUnsubscribeServiceTypes")]
    public partial class SubscribeUnsubscribeServiceResponse
    {

        private ResponseHead responseHeadField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public ResponseHead ResponseHead
        {
            get
            {
                return this.responseHeadField;
            }
            set
            {
                this.responseHeadField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.mycas.org.uk/services/SubscribeUnsubscribeService")]
    public partial class subscribeUnsubscribeServiceResponse
    {

        private SubscribeUnsubscribeServiceResponse subscribeUnsubscribeServiceResponse1Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subscribeUnsubscribeServiceResponse", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public SubscribeUnsubscribeServiceResponse subscribeUnsubscribeServiceResponse1
        {
            get
            {
                return this.subscribeUnsubscribeServiceResponse1Field;
            }
            set
            {
                this.subscribeUnsubscribeServiceResponse1Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.mycas.org.uk/schemas/SubscribeUnsubscribeServiceTypes")]
    public enum RequestBodyOperationCode
    {

        /// <remarks/>
        S,

        /// <remarks/>
        U,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class subscribeUnsubscribeServiceRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://www.mycas.org.uk/services/SubscribeUnsubscribeService", Order = 0)]
        public subscribeUnsubscribeService subscribeUnsubscribeService;

        public subscribeUnsubscribeServiceRequest1()
        {
        }

        public subscribeUnsubscribeServiceRequest1(subscribeUnsubscribeService subscribeUnsubscribeService)
        {
            this.subscribeUnsubscribeService = subscribeUnsubscribeService;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class subscribeUnsubscribeServiceResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "https://www.mycas.org.uk/services/SubscribeUnsubscribeService", Order = 0)]
        public subscribeUnsubscribeServiceResponse subscribeUnsubscribeServiceResponse;

        public subscribeUnsubscribeServiceResponse1()
        {
        }

        public subscribeUnsubscribeServiceResponse1(subscribeUnsubscribeServiceResponse subscribeUnsubscribeServiceResponse)
        {
            this.subscribeUnsubscribeServiceResponse = subscribeUnsubscribeServiceResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SubscribeUnsubscribeServiceChannel : SubscribeUnsubscribeService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubscribeUnsubscribeServiceClient : System.ServiceModel.ClientBase<SubscribeUnsubscribeService>, SubscribeUnsubscribeService
    {

        public SubscribeUnsubscribeServiceClient()
        {
        }

        public SubscribeUnsubscribeServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public SubscribeUnsubscribeServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public SubscribeUnsubscribeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public SubscribeUnsubscribeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        subscribeUnsubscribeServiceResponse1 SubscribeUnsubscribeService.subscribeUnsubscribeService(subscribeUnsubscribeServiceRequest1 request)
        {
            return base.Channel.subscribeUnsubscribeService(request);
        }

        public subscribeUnsubscribeServiceResponse subscribeUnsubscribeService(subscribeUnsubscribeService subscribeUnsubscribeService1)
        {
            subscribeUnsubscribeServiceRequest1 inValue = new subscribeUnsubscribeServiceRequest1();
            inValue.subscribeUnsubscribeService = subscribeUnsubscribeService1;
            subscribeUnsubscribeServiceResponse1 retVal = ((SubscribeUnsubscribeService)(this)).subscribeUnsubscribeService(inValue);
            return retVal.subscribeUnsubscribeServiceResponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<subscribeUnsubscribeServiceResponse1> SubscribeUnsubscribeService.subscribeUnsubscribeServiceAsync(subscribeUnsubscribeServiceRequest1 request)
        {
            return base.Channel.subscribeUnsubscribeServiceAsync(request);
        }

        public System.Threading.Tasks.Task<subscribeUnsubscribeServiceResponse1> subscribeUnsubscribeServiceAsync(subscribeUnsubscribeService subscribeUnsubscribeService)
        {
            subscribeUnsubscribeServiceRequest1 inValue = new subscribeUnsubscribeServiceRequest1();
            inValue.subscribeUnsubscribeService = subscribeUnsubscribeService;
            return ((SubscribeUnsubscribeService)(this)).subscribeUnsubscribeServiceAsync(inValue);
        }
    }
    namespace www.mycas.org.uk.services.SubscribeUnsubscribeService
    {


        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
        [System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
        public partial class Exception : object, System.Xml.Serialization.IXmlSerializable
        {

            private System.Xml.XmlNode[] nodesField;

            private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("Exception", "https://www.mycas.org.uk/services/SubscribeUnsubscribeService");

            public System.Xml.XmlNode[] Nodes
            {
                get
                {
                    return this.nodesField;
                }
                set
                {
                    this.nodesField = value;
                }
            }

            public void ReadXml(System.Xml.XmlReader reader)
            {
                this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
            }

            public void WriteXml(System.Xml.XmlWriter writer)
            {
                System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
            }

            public System.Xml.Schema.XmlSchema GetSchema()
            {
                return null;
            }

            public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
            {
                System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
                return typeName;
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
        [System.Xml.Serialization.XmlRootAttribute(IsNullable = false)]
        public partial class ServiceException : object, System.Xml.Serialization.IXmlSerializable
        {

            private System.Xml.XmlNode[] nodesField;

            private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ServiceException", "https://www.mycas.org.uk/services/SubscribeUnsubscribeService");

            public System.Xml.XmlNode[] Nodes
            {
                get
                {
                    return this.nodesField;
                }
                set
                {
                    this.nodesField = value;
                }
            }

            public void ReadXml(System.Xml.XmlReader reader)
            {
                this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
            }

            public void WriteXml(System.Xml.XmlWriter writer)
            {
                System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
            }

            public System.Xml.Schema.XmlSchema GetSchema()
            {
                return null;
            }

            public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
            {
                System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
                return typeName;
            }
        }
    }
}