//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.AcknowledgeNotificationService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.mycas.org.uk/service/notification/AcknowledgeNotificationService")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.mycas.org.uk/schemas/CommonTypes")]
    public partial class ResponseHead : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseCodeField;
        
        private string responseMessageField;
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ResponseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                this.responseMessageField = value;
                this.RaisePropertyChanged("ResponseMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.mycas.org.uk/schemas/notifications/AcknowledgeNotificationTypes")]
    public partial class AcknowledgeNotificationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseHead responseHeadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResponseHead ResponseHead {
            get {
                return this.responseHeadField;
            }
            set {
                this.responseHeadField = value;
                this.RaisePropertyChanged("ResponseHead");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.mycas.org.uk/service/notification/AcknowledgeNotificationService")]
    public partial class acknowledgeNotificationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AcknowledgeNotificationResponse acknowledgeNotificationResponse1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("acknowledgeNotificationResponse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AcknowledgeNotificationResponse acknowledgeNotificationResponse1 {
            get {
                return this.acknowledgeNotificationResponse1Field;
            }
            set {
                this.acknowledgeNotificationResponse1Field = value;
                this.RaisePropertyChanged("acknowledgeNotificationResponse1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.mycas.org.uk/schemas/notifications/CommonNotificationTypes")]
    public partial class Notification : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string notificationIDField;
        
        private string notificationTypeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NotificationID {
            get {
                return this.notificationIDField;
            }
            set {
                this.notificationIDField = value;
                this.RaisePropertyChanged("NotificationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NotificationTypeCode {
            get {
                return this.notificationTypeCodeField;
            }
            set {
                this.notificationTypeCodeField = value;
                this.RaisePropertyChanged("NotificationTypeCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.mycas.org.uk/schemas/notifications/AcknowledgeNotificationTypes")]
    public partial class RequestBody : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Notification notificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Notification Notification {
            get {
                return this.notificationField;
            }
            set {
                this.notificationField = value;
                this.RaisePropertyChanged("Notification");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.mycas.org.uk/schemas/notifications/AcknowledgeNotificationTypes")]
    public partial class AcknowledgeNotificationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestBody requestBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RequestBody RequestBody {
            get {
                return this.requestBodyField;
            }
            set {
                this.requestBodyField = value;
                this.RaisePropertyChanged("RequestBody");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.mycas.org.uk/service/notification/AcknowledgeNotificationService")]
    public partial class acknowledgeNotification : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AcknowledgeNotificationRequest acknowledgeNotificationRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AcknowledgeNotificationRequest acknowledgeNotificationRequest {
            get {
                return this.acknowledgeNotificationRequestField;
            }
            set {
                this.acknowledgeNotificationRequestField = value;
                this.RaisePropertyChanged("acknowledgeNotificationRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.mycas.org.uk/service/notification/AcknowledgeNotificationService")]
    public partial class ServiceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string exceptionStackTraceField;
        
        private string messageField;
        
        private string messageIdField;
        
        private string[] placeHolderValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string exceptionStackTrace {
            get {
                return this.exceptionStackTraceField;
            }
            set {
                this.exceptionStackTraceField = value;
                this.RaisePropertyChanged("exceptionStackTrace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("messageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("placeHolderValues", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string[] placeHolderValues {
            get {
                return this.placeHolderValuesField;
            }
            set {
                this.placeHolderValuesField = value;
                this.RaisePropertyChanged("placeHolderValues");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.mycas.org.uk/service/notification/AcknowledgeNotificationService", ConfigurationName="AcknowledgeNotificationService.AcknowledgeNotificationService")]
    public interface AcknowledgeNotificationService {
        
        // CODEGEN: Generating message contract since the operation acknowledgeNotification is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="https://www.mycas.org.uk/service/AcknowledgeNotificationService/acknowledgeNotifi" +
            "cation", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsFormsApplication1.AcknowledgeNotificationService.Exception), Action="https://www.mycas.org.uk/service/AcknowledgeNotificationService/acknowledgeNotifi" +
            "cation", Name="Exception")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsFormsApplication1.AcknowledgeNotificationService.ServiceException), Action="https://www.mycas.org.uk/service/AcknowledgeNotificationService/acknowledgeNotifi" +
            "cation", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotificationResponse1 acknowledgeNotification(WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotificationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.mycas.org.uk/service/AcknowledgeNotificationService/acknowledgeNotifi" +
            "cation", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotificationResponse1> acknowledgeNotificationAsync(WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotificationRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class acknowledgeNotificationRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.mycas.org.uk/service/notification/AcknowledgeNotificationService")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CallerToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.mycas.org.uk/service/notification/AcknowledgeNotificationService", Order=0)]
        public WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotification acknowledgeNotification;
        
        public acknowledgeNotificationRequest1() {
        }
        
        public acknowledgeNotificationRequest1(string CallerToken, WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotification acknowledgeNotification) {
            this.CallerToken = CallerToken;
            this.acknowledgeNotification = acknowledgeNotification;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class acknowledgeNotificationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.mycas.org.uk/service/notification/AcknowledgeNotificationService", Order=0)]
        public WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotificationResponse acknowledgeNotificationResponse;
        
        public acknowledgeNotificationResponse1() {
        }
        
        public acknowledgeNotificationResponse1(WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotificationResponse acknowledgeNotificationResponse) {
            this.acknowledgeNotificationResponse = acknowledgeNotificationResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AcknowledgeNotificationServiceChannel : WindowsFormsApplication1.AcknowledgeNotificationService.AcknowledgeNotificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AcknowledgeNotificationServiceClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.AcknowledgeNotificationService.AcknowledgeNotificationService>, WindowsFormsApplication1.AcknowledgeNotificationService.AcknowledgeNotificationService {
        
        public AcknowledgeNotificationServiceClient() {
        }
        
        public AcknowledgeNotificationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AcknowledgeNotificationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcknowledgeNotificationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcknowledgeNotificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotificationResponse1 WindowsFormsApplication1.AcknowledgeNotificationService.AcknowledgeNotificationService.acknowledgeNotification(WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotificationRequest1 request) {
            return base.Channel.acknowledgeNotification(request);
        }
        
        public WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotificationResponse acknowledgeNotification(string CallerToken, WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotification acknowledgeNotification1) {
            WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotificationRequest1 inValue = new WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotificationRequest1();
            inValue.CallerToken = CallerToken;
            inValue.acknowledgeNotification = acknowledgeNotification1;
            WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotificationResponse1 retVal = ((WindowsFormsApplication1.AcknowledgeNotificationService.AcknowledgeNotificationService)(this)).acknowledgeNotification(inValue);
            return retVal.acknowledgeNotificationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotificationResponse1> WindowsFormsApplication1.AcknowledgeNotificationService.AcknowledgeNotificationService.acknowledgeNotificationAsync(WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotificationRequest1 request) {
            return base.Channel.acknowledgeNotificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotificationResponse1> acknowledgeNotificationAsync(string CallerToken, WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotification acknowledgeNotification) {
            WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotificationRequest1 inValue = new WindowsFormsApplication1.AcknowledgeNotificationService.acknowledgeNotificationRequest1();
            inValue.CallerToken = CallerToken;
            inValue.acknowledgeNotification = acknowledgeNotification;
            return ((WindowsFormsApplication1.AcknowledgeNotificationService.AcknowledgeNotificationService)(this)).acknowledgeNotificationAsync(inValue);
        }
    }
}
